services:
  db:
    image: postgres
    container_name: example_db # TODO: Update value
    restart: always
    env_file:
      - ./.env
    ports:
      - 5480:5432 # TODO: If you have more containers, update the external port
    volumes:
      - .data:/var/lib/postgresql

  web:
    container_name: example_web # TODO: Update value
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8050:8000" # TODO: If you have more containers, update the external port
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always
