services:
  db:
    image: postgres
    container_name: example_db # Update
    restart: always
    environment:
      POSTGRES_DB: example_db # Update
      POSTGRES_USER: example_user # Update
      POSTGRES_PASSWORD: example_password # Update
    ports:
      - 5432:5432
    volumes:
      - .data:/var/lib/postgresql

  web:
    container_name: example_web # Update
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
    restart: always
